class ItemSets
  ORDER = [
    'Zenny',
    'Iron Ore',
    'Machalite Ore',
    'Dragonite Ore',
    'Earth Crystal',
    'Monster Bone S',
    'Monster Bone M',
    'Monster Bone L',
    'Monster Bone+',
    'Fire Herb',
    'Flowfern',
    'Snow Herb',
    'Sleep Herb',
    'Parashroom',
    'Toadstool',
    'Thunderbug',
    'Godbug',
    'Carpenterbug',
    'Sharp Claw',
    'Wingdrake Hide',
    'Great Jagras Scale',
    'Great Jagras Hide',
    'Great Jagras Claw',
    'Great Jagras Mane',
    'Great Jagras Primescale',
    'Fanged Wyvern Gem',
    'Wyvern Gem Shard',
    'Kulu-Ya-Ku Scale',
    'Kulu-Ya-Ku Hide',
    'Kulu-Ya-Ku Beak',
    'Kulu-Ya-Ku Plume',
    'Kulu-Ya-Ku Primescale',
    'Kulu-Ya-Ku Primehide',
    'Pukei-Pukei Scale',
    'Pukei-Pukei Shell',
    'Pukei-Pukei Tail',
    'Pukei-Pukei Sac',
    'Pukei-Pukei Quill',
    'Pukei-Pukei Primescale',
    'Barroth Shell',
    'Barroth Claw',
    'Barroth Tail',
    'Barroth Scalp',
    'Barroth Ridge',
    'Barroth Primeshell',
    'Great Girros Scale',
    'Great Girros Fang',
    'Great Girros Tail',
    'Great Girros Hood',
    'Great Girros Primescale',
    'Great Girros Primefang',
    'Tobi-Kadachi Scale',
    'Tobi-Kadachi Claw',
    'Tobi-Kadachi Pelt',
    'Tobi-Kadachi Membrane',
    'Tobi-Kadachi Primescale',
    'Tobi-Kadachi Electrode',
    'Paolumu Scale',
    'Paolumu Pelt',
    'Paolumu Webbing',
    'Paolumu Shell',
    'Paolumu Primescale',
    'Paolumu Primeshell',
    'Jyuratodus Shell',
    'Jyuratodus Scale',
    'Jyuratodus Fang',
    'Jyuratodus Fin',
    'Jyuratodus Primescale',
    'Jyuratodus Primeshell',
    'Anjanath Scale',
    'Anjanath Fang',
    'Anjanath Tail',
    'Anjanath Nosebone',
    'Anjanath Primescale',
    'Anjanath Plate',
    'Rathian Scale',
    'Rathian Shell',
    'Rathian Webbing',
    'Rathian Spike',
    'Rathian Primescale',
    'Rathian Plate',
    'Pink Rathian Scale',
    'Pink Rathian Shell',
    'Pink Rathian Webbing',
    'Pink Rathian Spike',
    'Pink Rathian Primescale',
    'Pink Rathian Plate',
    'Legiana Scale',
    'Legiana Hide',
    'Legiana Claw',
    'Legiana Webbing',
    'Legiana Primescale',
    'Legiana Plate',
    'Diablos Shell',
    'Diablos Fang',
    'Diablos Tailcase',
    'Diablos Ridge',
    'Diablos Primeshell',
    'Diablos Marrow',
    'Black Diablos Fang',
    'Black Diablos Shell',
    'Black Diablos Tailcase',
    'Black Diablos Ridge',
    'Black Diablos Primeshell',
    'Black Diablos Marrow',
    'Rathalos Scale',
    'Rathalos Wingtalon',
    'Rathalos Tail',
    'Rathalos Marrow',
    'Rathalos Primescale',
    'Rathalos Plate',
    'Azure Rathalos Scale',
    'Azure Rathalos Wingtalon',
    'Azure Rathalos Tail',
    'Azure Rathalos Marrow',
    'Azure Rathalos Primescale',
    'Azure Rathalos Plate',
    'Radobaan Scale',
    'Radobaan Shell',
    'Radobaan Tail',
    'Radobaan Oilshell',
    'Radobaan Primescale',
    'Radobaan Marrow',
    'Banbaro Shell',
    'Banbaro Ridge',
    'Banbaro Tail',
    'Banbaro Pelt',
    'Banbaro Primeshell',
    'Banbaro Great Horn',
    'Barioth Claw',
    'Barioth Shell',
    'Barioth Tail',
    'Barioth Spike',
    'Barioth Primeclaw',
    'Amber Fang',
    'Zinogre Claw',
    'Zinogre Shell',
    'Zinogre Tail',
    'Zinogre Shockfur',
    'Zinogre Primeclaw',
    'Zinogre Horn',
    'Zinogre Plate',
    'Pumpkin Ticket',
    '2024 Weapon Ticket',
    '2024 Armor Ticket',
    'Weapon Refining Parts',
    'Armor Refining Parts',
  ]

  SETS = {
    Zenny: ['Zenny'],
    Ores: ['Iron Ore', 'Machalite Ore', 'Dragonite Ore', 'Earth Crystal'],
    Bones: ['Monster Bone S', 'Monster Bone M', 'Monster Bone L', 'Monster Bone+'],
    Vegetation: ['Fire Herb', 'Flowfern', 'Snow Herb', 'Sleep Herb', 'Parashroom', 'Toadstool', 'Thunderbug', 'Godbug', 'Carpenterbug'],
    'Small Monster': ['Sharp Claw', 'Wingdrake Hide'],
    'Great Jagras': ['Great Jagras Scale', 'Great Jagras Hide', 'Great Jagras Claw', 'Great Jagras Mane', 'Great Jagras Primescale', 'Fanged Wyvern Gem', 'Wyvern Gem Shard'],
    'Kulu-Ya-Ku': ['Kulu-Ya-Ku Scale', 'Kulu-Ya-Ku Hide', 'Kulu-Ya-Ku Beak', 'Kulu-Ya-Ku Plume', 'Kulu-Ya-Ku Primescale', 'Kulu-Ya-Ku Primehide'],
    'Pukei-Pukei': ['Pukei-Pukei Scale', 'Pukei-Pukei Shell', 'Pukei-Pukei Tail', 'Pukei-Pukei Sac', 'Pukei-Pukei Quill', 'Pukei-Pukei Primescale'],
    Barroth: ['Barroth Shell', 'Barroth Claw', 'Barroth Tail', 'Barroth Scalp', 'Barroth Ridge', 'Barroth Primeshell'],
    'Great Girros': ['Great Girros Scale', 'Great Girros Fang', 'Great Girros Tail', 'Great Girros Hood', 'Great Girros Primescale', 'Great Girros Primefang'],
    'Tobi-Kadachi': ['Tobi-Kadachi Scale', 'Tobi-Kadachi Claw', 'Tobi-Kadachi Pelt', 'Tobi-Kadachi Membrane', 'Tobi-Kadachi Primescale', 'Tobi-Kadachi Electrode'],
    Paolumu: ['Paolumu Scale', 'Paolumu Pelt', 'Paolumu Webbing', 'Paolumu Shell', 'Paolumu Primescale', 'Paolumu Primeshell'],
    Jyuratodus: ['Jyuratodus Shell', 'Jyuratodus Scale', 'Jyuratodus Fang', 'Jyuratodus Fin', 'Jyuratodus Primescale', 'Jyuratodus Primeshell'],
    Anjanath: ['Anjanath Scale', 'Anjanath Fang', 'Anjanath Tail', 'Anjanath Nosebone', 'Anjanath Primescale', 'Anjanath Plate'],
    Rathian: ['Rathian Scale', 'Rathian Shell', 'Rathian Webbing', 'Rathian Spike', 'Rathian Primescale', 'Rathian Plate'],
    'Pink Rathian': ['Pink Rathian Scale', 'Pink Rathian Shell', 'Pink Rathian Webbing', 'Pink Rathian Spike', 'Pink Rathian Primescale', 'Pink Rathian Plate'],
    Legiana: ['Legiana Scale', 'Legiana Hide', 'Legiana Claw', 'Legiana Webbing', 'Legiana Primescale', 'Legiana Plate'],
    Diablos: ['Diablos Shell', 'Diablos Fang', 'Diablos Tailcase', 'Diablos Ridge', 'Diablos Primeshell', 'Diablos Marrow'],
    'Black Diablos': ['Black Diablos Fang', 'Black Diablos Shell', 'Black Diablos Tailcase', 'Black Diablos Ridge', 'Black Diablos Primeshell', 'Black Diablos Marrow'],
    Rathalos: ['Rathalos Scale', 'Rathalos Wingtalon', 'Rathalos Tail', 'Rathalos Marrow', 'Rathalos Primescale', 'Rathalos Plate'],
    'Azure Rathalos': ['Azure Rathalos Scale', 'Azure Rathalos Wingtalon', 'Azure Rathalos Tail', 'Azure Rathalos Marrow', 'Azure Rathalos Primescale', 'Azure Rathalos Plate'],
    Radobaan: ['Radobaan Scale', 'Radobaan Shell', 'Radobaan Tail', 'Radobaan Oilshell', 'Radobaan Primescale', 'Radobaan Marrow'],
    Banbaro: ['Banbaro Shell', 'Banbaro Ridge', 'Banbaro Tail', 'Banbaro Pelt', 'Banbaro Primeshell', 'Banbaro Great Horn'],
    Barioth: ['Barioth Claw', 'Barioth Shell', 'Barioth Tail', 'Barioth Spike', 'Barioth Primeclaw', 'Amber Fang'],
    Zinogre: ['Zinogre Claw', 'Zinogre Shell', 'Zinogre Tail', 'Zinogre Shockfur', 'Zinogre Primeclaw', 'Zinogre Horn', 'Zinogre Plate'],
    Tickets: ['Pumpkin Ticket', '2024 Weapon Ticket', '2024 Armor Ticket'],
    'Refining Parts': ['Weapon Refining Parts', 'Armor Refining Parts'],
  }

  def self.update_order
    ORDER.each.with_index { |name, i|
      Item.find_by(name: name).update(sort_order: i)
    }
  end

  def self.all_by_set
    SETS.transform_values &method(:by_names)
  end

  def self.by_names(*names)
    Item.where(name: names).order(:sort_order)
  end

  def self.by_set(set)
    names = SETS.fetch(set.to_sym, [])
    Item.where(name: names).order(:sort_order)
  end
end
